[package]
name = "key-overlay"
version = "1.0.0"
edition = "2021"


[dependencies]
device_query = "1.0.0"
sdl2 = { version = "0.35.2", features = ["ttf", "unsafe_textures"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"